### PR TITLE
Issue #839 JavaLogFactory ConcMod

### LINKED ISSUE #839: ConcurrentModificationException
#### Describe the bug
JavaLogFactory.java's readLoggerConfiguration function throws ConcurrentModificationException at this line 
```java
if (System.getProperties().keySet().stream().anyMatch(propKey ->
        "java.util.logging.config.class".equals(propKey) || "java.util.logging.config.file".equals(propKey)))
```
in a multi-threaded environment when another thread is concurrently setting system properties while ESAPI is iterating over system properties.

#### Specify what ESAPI version(s) you are experiencing this bug in
2.5.2.0

#### To Reproduce
```java
public class Reproduce {
    public static void main(String[] args) {
        Thread t = new Thread(new Runnable() {
            public void run() {
                while (true) {
                    long time = System.currentTimeMillis();
                    // Emulate another thread modifying system properties
                    System.setProperty(time + "", time + "");
                    try {
                        Thread.sleep(500);
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }
                }
            }
        }); t.start();
        EsapiThread esapiThread = new EsapiThread();
        esapiThread.start();
    }

    private static class EsapiThread extends Thread {
        public void run() {
            // Emulate the code of JavaLogFactory in ESAPI
            System.getProperties().keySet().stream().anyMatch(a -> {
                try {
                    Thread.sleep(2000);
                } catch (InterruptedException e) {
                    throw new RuntimeException(e);
                }
                return "dummy".equals(a);
            });
        }
    }
}

```

#### Expected behavior
Proposed change: copy the `System.getProperties().keySet()` to a new collection and iterating over the new collection instead of the original one to avoid thread safety problem.

#### Platform environment (please complete the following information)
 - JDK version: JDK8

### PR DESCRIPTION
**Pull request by jeremiahjstacey**
Removing support for esapi-java-logging.properties file from baseline.

ConfigurationException is thrown if file is found on the path at runtime.  Exception message links to a wiki page with instructions on how to configure the application instance.

Closes #839 
Also note the wiki page  has been created.
https://github.com/ESAPI/esapi-java-legacy/wiki/Configuring-the-JavaLogFactory

### CODE REVIEW

**Comment by kwwall** [comment]
@jeremiahjstacey - Do you think it's useful to mention the previous defaults that were in the (now removed -- after this PR is merged) esapi-java-logging.properties file that used to be in the ESAPI configuration jar? I thought we may get questions about what properties used to be there for JUL and thought we could drop those into the new wiki page (https://github.com/ESAPI/esapi-java-legacy/wiki/Configuring-the-JavaLogFactory) that you wrote.

File: src/main/java/org/owasp/esapi/logging/java/JavaLogFactory.java [hunk 1]
```diff
@@ -93,43 +93,24 @@ public class JavaLogFactory implements LogFactory {
...
+         * 
+         * Verify the file is not present and fail if found to enforce understanding of
+         * the configuration method.
          */
         try (InputStream stream = JavaLogFactory.class.getClassLoader().
                 getResourceAsStream("esapi-java-logging.properties")) {
-            if (stream == null) {
-                throw new ConfigurationException("Unable to locate resource: esapi-java-logging.properties");
+            if (stream != null) {
+                throw new ConfigurationException("esapi-java-logging.properties is no longer supported.  See https://github.com/ESAPI/esapi-java-legacy/wiki/Configuring-the-JavaLogFactory for information on corrective actions.");
```
Comment (kwwall) [inline src/main/java/org/owasp/esapi/logging/java/JavaLogFactory.java:106]: I think it would make more sense to define this exception message as `final String ` and the reference it both places. That way, if we every decide to change the error message, we won't forget to change one of the instances. Otherwise, I think this is great and hopefully it will head off questions from those who seem to have a habit of never reading the release notes.

File: src/main/java/org/owasp/esapi/logging/java/JavaLogFactory.java [hunk 2]
```diff
@@ -93,43 +93,24 @@ public class JavaLogFactory implements LogFactory {
...
             }
-            logManager.readConfiguration(stream);
+
         } catch (IOException ioe) {
-            throw new ConfigurationException("Failed to load esapi-java-logging.properties.", ioe);
+            // This is a little strange, I know.
+            // If the IOException is thrown, then the file actually exists but is malformatted or has some other issue.
+            // The file should not exist at all, so use the same message as above but include the original exception in the log as well.
```
Comment (kwwall) [inline src/main/java/org/owasp/esapi/logging/java/JavaLogFactory.java:112]: See previous comment so only have to change it in one place to ensure consistency.

File: src/test/java/org/owasp/esapi/logging/java/JavaLogFactoryTest.java [hunk 3]
```diff
@@ -48,83 +43,6 @@ public class JavaLogFactoryTest {
     @Rule
     public ExpectedException exEx = ExpectedException.none();
 
-    @Test
```
Comment (kwwall) [inline src/test/java/org/owasp/esapi/logging/java/JavaLogFactoryTest.java:51]: So, we're not going to try to test the case if the `ConfigurationException` is thrown if the file **esapi-java-logging.properties** is found. As long as you tested all the cases separately, I guess I'm okay with that, otherwise the testing gets messy because you have to create the file, test, delete it, and test again.

**Review by kwwall — APPROVED** [review]
@jeremiahjstacey - Some minor suggestions is all, but I'm okay with this PR as it is.

@xeno6696 - I may try doing a release over Memorial Day weekend (no promise though), so if I will give you until Sat around noon if you want to review this. Ideally, just leave an 'approved' as early as possible so I know you're good with it.

File: src/test/java/org/owasp/esapi/logging/java/JavaLogFactoryTest.java (hunk 3 above)
Comment (jeremiahjstacey) [reply src/test/java/org/owasp/esapi/logging/java/JavaLogFactoryTest.java:51]: Yeah, I went light on the testing with this change as we'd have to be testing a negative condition.

I am relying on the implied tested state from all of the other tests - knowing that the properties file has been removed and the configuration has changed, all existing tests continue to function.

File: src/main/java/org/owasp/esapi/logging/java/JavaLogFactory.java (hunk 1 above)
Comment (jeremiahjstacey) [reply src/main/java/org/owasp/esapi/logging/java/JavaLogFactory.java]: Update applied

File: src/main/java/org/owasp/esapi/logging/java/JavaLogFactory.java (hunk 2 above)
Comment (jeremiahjstacey) [reply src/main/java/org/owasp/esapi/logging/java/JavaLogFactory.java:112]: Tracking in conversation above.  Resolving this thread in favor of the previous conversation.

File: src/test/java/org/owasp/esapi/logging/java/JavaLogFactoryTest.java (hunk 3 above)
Comment (xeno6696) [reply src/test/java/org/owasp/esapi/logging/java/JavaLogFactoryTest.java:51]: Sorry I'm late to the party.  Kids birthday this weekend and family's in town.  

Regression tests FTW.  I have no issues here.

**Review by xeno6696 — APPROVED** [review]
