### PR TITLE
Logger Level Logic Updates

### LINKED ISSUE #630: Incorrrect result for `isEnabled()` in `Slf4JLogger`
`isEnabled(int esapiLevel)` in `Slf4JLogger` returns incorrect result. Mostly due to the OR condition `maxLogLevel == Logger.ALL`.

## Steps to reproduce (in 2.2.3.1)
* Create a logger for `SomeClass` in log4j.xml. Set its level to `info` level. Like so:
```
<Logger name="com.SomeClass" level="info">
    <appender-ref ref="SOME-APPENDER-REF"/>
</Logger>
```
* `SomeClass` looks like:
```
private static final Logger LOG = ESAPI.getLogger(SomeClass.class);;
...
if(LOG.isDebugEnabled()) {
    // do some heavy operation here. 
}
```

## Expected result
* With above logger config `LOG.isDebugEnabled()` will return `false`. 

## Actual result
* `LOG.isDebugEnabled()` returns `true`.

## Some more observations
* Even though the enabled checks (like `isDebugEnabled()`, `isInfoEnabled()`, etc.) fail, the actual log statements (like `debug()`, `info()`) do honor the log levels. 
* This has a big perf impact because of all the crap that might go in `LOG.isDebugEnabled()` check.

### PR DESCRIPTION
**Pull request by jeremiahjstacey**
Closes #630 

Tests updated to reflect desired results of `isEnabled` for each of the loggers.
Logic updated to inverse the evaluate such that the method parameter must be greater than or equal to the configured logging level.
The field `maxLogLevel` has been renamed to `loggingLevel`

### CODE REVIEW

File: src/main/java/org/owasp/esapi/logging/java/JavaLogger.java [hunk 1]
```diff
@@ -52,8 +52,7 @@ private void log(int esapiLevel, EventType type, String message, Throwable throw
 
 
     private boolean isEnabled(int esapiLevel) {
-        //Are Logger.OFF and Logger.ALL reversed?  This should be simply the less than or equal to check...
-        return (esapiLevel <= maxLogLevel && maxLogLevel != Logger.OFF) || maxLogLevel == Logger.ALL;
+        return esapiLevel >= loggingLevel;
```
Comment (jeremiahjstacey) [inline src/main/java/org/owasp/esapi/logging/java/JavaLogger.java:55]: This is the logic update in each file.  All other changes are just the rename event.
